[Backend] views, urls
swsnu/swpp2021-team9 pull request #46
Opened 2021-11-14 03:50 UTC by zz-zye

### Related Issues

Fixes #45 

### Description

`backend/app/band`에 `urls.py`와 `views.py`를 만들어 보았습니다.

SWPP 과제에서 하던 대로 `views.py`에 모든 함수를 다 넣으려고 하니 좀 길다는 느낌이 드는데, 이 한 파일을 베이스로 협업해도 괜찮을까요? 아니면 다른 대안이 있을까요?

### Additional documentation

아래와 같이 `views.py`에 method별 함수만 만들었습니다.

```python
# user views

def userSignup(request: HttpRequest):
    if request.method == 'POST':
        return HttpResponse(status=201)
    else:
        return HttpResponseNotAllowed(['POST'])
...

# instrument views

def instrument(request: HttpRequest):
    if request.method == 'GET':
        return HttpResponse(status=200)
    else:
        return HttpResponseNotAllowed(['GET'])
...
```

2021-11-15 14:07 UTC, zz-zye commented
현재 Django REST Framework를 사용해 간단히 serializers.py까지 만들었고, View들은 Class 형태로 하였습니다. SWPP에서 한 것처럼 함수 형태로 할 경우 'GET', 'POST' 등을 전부 하나의 함수에서 처리하게 되는데 그게 SonarCloud상에서는 부적절한 코드로 나오더라구요.

또한 view마다 간단한 test를 작성했습니다.

2021-11-15 14:38 UTC, zz-zye commented
![image](https://user-images.githubusercontent.com/77932817/141800224-1ca47173-71b0-4f95-8f29-90d27b367fce.png)

위와 같이 id가 일종의 keyword라서 바꿔야 한다는 warning이 있어서, urls.py에 있는 id들을 snake_case로 변경했습니다.

![image](https://user-images.githubusercontent.com/77932817/141800391-fd50cb50-6ee9-4090-945e-030c207a8285.png)

2021-11-15 15:54 UTC, zz-zye commented
user 관련 view나 url은 `app/user`로 옮겼습니다.

![image](https://user-images.githubusercontent.com/77932817/141812808-42a3e047-5b6a-4c58-8191-979ab33307cb.png)


기본적인 테스트 파일도 작성했습니다.

![image](https://user-images.githubusercontent.com/77932817/141812782-f27552e9-a0b4-4b09-a595-deb7ba0140f0.png)

2021-11-15 16:21 UTC, ccdc-git requested changes
엄청 많이 구현하셨네요. 일단 main에 올리는 거니까 lint도 부탁드릴게요.

추가로 views/__init__.py 파일에 아무것도 안적으실거면 없어도 돼요.

2021-11-15 16:21 UTC, ccdc-git commented on backend/app/band/serializers.py
> +class InstrumentSerializer(serializers.HyperlinkedModelSerializer):
HyperlinkedModelSerializer 
이걸 쓰는 이유가 있나요?

2021-11-15 16:21 UTC, ccdc-git commented on backend/app/band/tests.py
> +from .models import Instrument, Song, Cover, Combination
필요없는 수정사항이네요

2021-11-15 16:21 UTC, ccdc-git commented on backend/app/band/urls.py
> +    path("user/signup/", user_views.UserSignup.as_view(), name="user_signup"),
user 관련한 url은 user/urls.py로 옮겨주세요.

2021-11-15 16:21 UTC, ccdc-git commented on backend/app/bandcruit/settings.py
> +        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
이거 넣으면 유저가 post 못하는거 아닌가요?

2021-11-15 16:21 UTC, ccdc-git commented on backend/app/band/views/test_combination.py
> +        client = Client(enforce_csrf_checks=True)
client = Client(enforce_csrf_checks=False)
이걸 사용하시면 csrf는 무시할 수 있어요.

2021-11-15 16:29 UTC, zz-zye commented on backend/app/band/admin.py
> +admin.site.register(CoverTag)
수정했습니다!

2021-11-15 16:29 UTC, zz-zye commented on backend/app/band/serializers.py
> +        fields = ["name"]
수정했습니다! 다른 serializer들에도 수정했습니다.

2021-11-15 16:30 UTC, zz-zye commented on backend/app/band/tests.py
> +from .models import Instrument, Song, Cover, Combination
아 하다보니까 몇 번 고치다가 결국에는 다시 원래대로 돌아왔는데, 자리가 바뀌었네요

2021-11-15 16:32 UTC, zz-zye commented on backend/app/band/serializers.py
> +class InstrumentSerializer(serializers.HyperlinkedModelSerializer):
이건 일단 DRF quickstart에 있는 그대로 가져왔습니다... 사실 아직 Serializer별 차이는 잘 모르겠습니다. 보통 어떤 걸 쓰나요?

2021-11-15 16:32 UTC, zz-zye commented on backend/app/band/tests.py
> +from .models import Instrument, Song, Cover, Combination
일단 뭐 다시 원래대로 고치기도 뭐하니 그대로 남기겠습니다

2021-11-15 16:35 UTC, zz-zye commented on backend/app/band/urls.py
> +    path("user/signup/", user_views.UserSignup.as_view(), name="user_signup"),
옮겼습니다!

2021-11-15 16:45 UTC, zz-zye commented on backend/app/band/views/test_combination.py
> +        client = Client(enforce_csrf_checks=True)
오 몰랐네요 감사합니다!

2021-11-15 16:50 UTC, zz-zye commented on backend/app/bandcruit/settings.py
> +        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
이것도 DRF의 [예시](https://www.django-rest-framework.org/#example)에서 가져왔는데요, 저도 아직 완전히는 모르지만 권한을 가진 유저는 POST, PUT 등도 가능하게 하고, 그게 아닌 unauthenticated 유저들에게는 Read-only만 가능하게 해주는 것 같습니다.

[참고](https://www.django-rest-framework.org/api-guide/permissions/#setting-the-permission-policy)

혹시 저희 프로젝트에 더 맞는 형태가 있을까요?

2021-11-15 16:54 UTC, zz-zye commented
> 추가로 `views/__init__.py` 파일에 아무것도 안적으실거면 없어도 돼요.

views를 하나의 모듈로 인식하려면 `__init__.py`가 필요하다고 합니다..!

![image](https://user-images.githubusercontent.com/77932817/141821654-aefb2694-cc06-48f7-ab7f-d4752e0fe7b7.png)

검색해보니까 최근에 와서는 필요없어졌다고 하는 글도 보이는데, 어째선지 제 VSCode에서는 `__init__.py`를 삭제하면 저 import 부분에서 빨간줄이 뜨네요..

2021-11-16 03:58 UTC, ccdc-git commented on backend/app/bandcruit/settings.py
> +        'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly'
로그인만 하면 post 가능한것 처럼 보이네요. 로그인 부분만 작동하면 문제 없을 것 같아요.

2021-11-16 04:03 UTC, ccdc-git commented on backend/app/band/serializers.py
> +class InstrumentSerializer(serializers.HyperlinkedModelSerializer):
저는 그냥 Serializer 나 ModelSerializer를 사용했었는데 HyperlinkedModelSerializer는 저희 디자인하고는 안맞는것 같네요.

2021-11-16 04:05 UTC, ccdc-git commented
" 랑 ' 는 lint적용에 상관없을텐데 왜 다 바꾼건가요?

2021-11-16 04:14 UTC, zz-zye commented
> " 랑 ' 는 lint적용에 상관없을텐데 왜 다 바꾼건가요?

아 제 VSCode 설정 때문에 자동으로 저장할 때마다 변환이 되었네요

2021-11-16 06:22 UTC, zz-zye commented on backend/app/band/serializers.py
> +class InstrumentSerializer(serializers.HyperlinkedModelSerializer):
ModelSerializer로 변경했습니다!

2021-11-16 06:23 UTC, GoGiants1 approved these changes
고생 많으셨습니다!

2021-11-16 06:23 UTC, GoGiants1 commented on backend/app/band/serializers.py
> +        fields = ["id", "name"]
이 Meta는 메타데이터를 말하는 건가요?

2021-11-16 06:32 UTC, zz-zye commented on backend/app/band/serializers.py
> +        fields = ["id", "name"]
맞는 것 같습니다. Django에서도 Model들 안에 metadata를 위한 `class Meta`가 있던데([참고](https://stackoverflow.com/questions/10344197/how-does-djangos-nested-meta-class-work)) 비슷한 것 같습니다.

[https://www.django-rest-framework.org/api-guide/serializers/#modelserializer](https://www.django-rest-framework.org/api-guide/serializers/#modelserializer)

2021-11-16 08:12 UTC, ccdc-git commented on backend/app/band/views/combination_views.py
> +        return HttpResponse(status=200)
아직 작동 안하는 코드들은 HttpResponse(status=501) 로 채워주는게 좋을 것 같습니다.
https://www.django-rest-framework.org/api-guide/status-codes/#server-error-5xx

2021-11-16 10:23 UTC, zz-zye commented on backend/app/band/views/combination_views.py
> +        return HttpResponse(status=200)
수정했습니다!

2021-11-16 10:39 UTC, ccdc-git approved these changes
수고하셨습니다.

2021-11-17 02:15 UTC, merged