Frontend/change waveform
swsnu/swpp2021-team9 pull request #49
Opened 2021-11-19 20:16 UTC by GoGiants1

### Related Issues

#20 

### Description

- 녹음 후 재생하는 player를 peaks.js로 변경.
- 파일 업로드 후 다시 듣는 기능 추가
- 음악 편집 기능 추가

### Additional documentation

2021-12-10 20:14 UTC, zz-zye requested changes
수고하셨습니다! 리뷰에서 답글 단 것 중에 그냥 바로 request changes 하기에 어려운 것도 있어서, 새 브랜치 `frontend/change_waveform_modified`에 수정사항을 반영해 보았습니다. 한 번 확인해주시면 감사하겠습니다!

2021-12-10 20:14 UTC, zz-zye commented on frontend/src/app/components/Peaks/Segment.tsx
> +          }}
이 부분에서 isMergeClicked를 갖고 변수를 바꾸는 것이 다소 복잡하게 느껴지는데, 여기 있는 isMerge 자체도 부모 컴포넌트로 옮기는 방식으로 간소화를 할 수 있지 않을까요? 이 부분은 바꾸기는 오래 걸릴 것 같아서 일단 답글 안 해주셔도 괜찮습니다.

2021-12-10 21:03 UTC, zz-zye commented
아 그리고 지금 왜인지 정확하지 않은데 처음 녹음 버튼을 눌러서 녹음한 것은 Zoom-in이 잘 안 되고, 그 다음 다시 녹음한 것부터 최대치로 Zoom-in이 된 상태로 시작하네요

```
const options: PeaksOptions = {
      containers: {
        overview: this.overviewWaveformRef.current,
        zoomview: this.zoomviewWaveformRef.current,
      },
...
```
혹시 Peaks에서 만들 때 처음에는 저게 가리키는 html 요소가 올바른 크기로 만들어져 있지 않은데, 두 번째 호출부터는 올바르게 만들어져있는 거랑 관련이 있을까요...? 저게 정확히 어떤 역할을 하는지 잘 몰라서 모르겠네요   
여기 options에 zoomLevels 등등 다양한 옵션을 줄 수 있던데 몇몇 개를 해봐도 해결되지는 않았습니다..

2021-12-11 02:19 UTC, GoGiants1 commented on frontend/src/app/components/Peaks/WaveformView.tsx
> +  peaks: any;
음 length 부분은 한 번 시도해보고 말씀드리겠습니다! 첫 번째 코멘트도 말씀해주신 부분 반영해보고 결정해보겠습니다.

2021-12-11 02:22 UTC, GoGiants1 commented on frontend/src/app/containers/CreateCoverPage/step1.tsx
> +      </React.Fragment>
네 그렇게 수정하도록 할게요!

2021-12-11 02:52 UTC, GoGiants1 commented on frontend/src/app/containers/CreateCoverPage/step1.tsx
> +  }, [isPlaySegmentClicked, segments, selectedSegmentId]);
감사합니다. 제안해주신 방법대로 수정하는게 더 간편한거 같아서 조금 더 단순화해서 적용시켰습니다. 클릭이 잘 안되는 거 같아서 클릭 이벤트를 td 태그로 옮겼습니다. 이제 잘 삭제됩니다. 아마도 버튼 클릭을 인식하는 범위가 너무 작았던거 같아요.

2021-12-11 03:08 UTC, GoGiants1 commented on frontend/src/app/containers/CreateCoverPage/step1.tsx
> +  }, [isPlaySegmentClicked, segments, selectedSegmentId]);
@zz-zye 음 바꾸어 보았는데, 이제는 waveform에서는 정상적으로 삭제되는데 table row가 삭제가 안되는군요 ..

2021-12-11 03:12 UTC, GoGiants1 commented on frontend/src/app/containers/CreateCoverPage/step1.tsx
> +  }, [isPlaySegmentClicked, segments, selectedSegmentId]);
` setSegments([...segs]);` 이렇게 바꿔서 해결했습니다. 같은 객체로 인식해서 리렌더링이 안되는거였네요.

2021-12-11 03:24 UTC, GoGiants1 commented on frontend/src/app/containers/CreateCoverPage/step1.tsx
> +  }, [createCoverState.audioURL, makeCombiState.song]);
넵 반영하였습니다

2021-12-11 03:27 UTC, GoGiants1 commented on frontend/src/app/containers/CreateCoverPage/step1.tsx
> +      });
이 부분은 삭제되었습니다

2021-12-11 03:27 UTC, GoGiants1 commented on frontend/src/app/components/Peaks/Segment.tsx
> +          }}
넵 급한거 처리하고 해보겠습니다.

2021-12-11 03:33 UTC, GoGiants1 commented
> 아 그리고 지금 왜인지 정확하지 않은데 처음 녹음 버튼을 눌러서 녹음한 것은 Zoom-in이 잘 안 되고, 그 다음 다시 녹음한 것부터 최대치로 Zoom-in이 된 상태로 시작하네요
> 
> ```
> const options: PeaksOptions = {
>       containers: {
>         overview: this.overviewWaveformRef.current,
>         zoomview: this.zoomviewWaveformRef.current,
>       },
> ...
> ```
> 
> 혹시 Peaks에서 만들 때 처음에는 저게 가리키는 html 요소가 올바른 크기로 만들어져 있지 않은데, 두 번째 호출부터는 올바르게 만들어져있는 거랑 관련이 있을까요...? 저게 정확히 어떤 역할을 하는지 잘 몰라서 모르겠네요 여기 options에 zoomLevels 등등 다양한 옵션을 줄 수 있던데 몇몇 개를 해봐도 해결되지는 않았습니다..

음 원래 첫 렌더링 될때 waveform의 zoom level이 정상적인것이고 두 번째부터는 지나치게 확대되어 보이는 상태였습니다. (샘플링에 관련한 라이브러리의 오류가 있었어요).

레벨이 다른게 사용자한테 불편할것 같아서 첫 번째, 두 번째 이후 렌더링, 둘 다 같은 줌 레벨이 적용되도록 설정을 수정하였습니다!

2021-12-11 04:15 UTC, zz-zye approved these changes
수고많으셨습니다!!

2021-12-11 07:15 UTC, ccdc-git reviewed
코드는 자세히 못보고 기능 위주로 봤는데 잘 작동하는 것 같아요. 
![image](https://user-images.githubusercontent.com/5417636/145668037-4f759d47-7191-418a-a77a-d46f231c0565.png)
id는 간단하게 숫자 하나로 보여줘도 될 것 같아요.
time은 적당히 0.000 으로 반올림해서 보여주는게 좋을 것 같아요.

![image](https://user-images.githubusercontent.com/5417636/145668074-23dc0d43-5ea8-4188-9e79-0ae12c7a1d60.png)
이부분 조정할때 오른쪽으로 가는거랑 왼쪽으로 가는거랑 구분해서 오른쪽으로 갈때 자연스럽게 움직이게 하는게 좋을 것 같아요

2021-12-11 07:15 UTC, ccdc-git commented on backend/app/band/views/cover_views.py
> +        print(data)
테스트 과정에 있는 print는 지워주세요

2021-12-11 07:15 UTC, ccdc-git commented on frontend/src/api/band/index.ts
> +    console.log(audiofile);
log 는 지워주세요

2021-12-11 07:20 UTC, GoGiants1 commented on backend/app/band/views/cover_views.py
> +        print(data)
지우고 다시 푸시했습니다

2021-12-11 07:25 UTC, GoGiants1 commented on frontend/src/api/band/index.ts
> +    console.log(audiofile);
넵 console log들도 삭제해서 푸시하겠습니다.

2021-12-11 07:31 UTC, GoGiants1 commented
> 코드는 자세히 못보고 기능 위주로 봤는데 잘 작동하는 것 같아요. ![image](https://user-images.githubusercontent.com/5417636/145668037-4f759d47-7191-418a-a77a-d46f231c0565.png) id는 간단하게 숫자 하나로 보여줘도 될 것 같아요. time은 적당히 0.000 으로 반올림해서 보여주는게 좋을 것 같아요.
> 
> ![image](https://user-images.githubusercontent.com/5417636/145668074-23dc0d43-5ea8-4188-9e79-0ae12c7a1d60.png) 이부분 조정할때 오른쪽으로 가는거랑 왼쪽으로 가는거랑 구분해서 오른쪽으로 갈때 자연스럽게 움직이게 하는게 좋을 것 같아요

time이랑 id 부분은 방금 반영하였습니다.

음 움직임 관련해서는 peaks.js랑 관련있는건데 나중에 어떤게 부자연스러운지 자세히 말씀해주실 수 있을까요?

2021-12-14 02:52 UTC, ccdc-git commented
막대기를 오른쪽으로 옮기면 네모 박스가 자연스럽게 따라 움직이지 않고 영역밖으로 나가면 막대기 오른쪽으로 가게 되어있어서 끊기는 느낌이 들어요

2021-12-14 07:42 UTC, ccdc-git approved these changes

2021-12-14 07:43 UTC, merged

2021-12-14 07:50 UTC, GoGiants1 commented
Close #20