[Backend] Cover Views
swsnu/swpp2021-team9 pull request #60
Opened 2021-11-25 11:51 UTC by zz-zye

### Related Issues

Fixes #59 

### Description

`/cover/<songid:int>/`, `/cover/<songid:int>/<instrumentid:int>/`, `/cover/like/<id:int>/`를 구현했습니다.

현재 Login이 없는 상태인 관계로, cover를 새로 등록할 때는 User를 None으로 하고, like를 했는지 가져올 때에는 무조건 User model의 첫 번째 User를 기준으로 했습니다.

Like를 위해 Cover의 like 정보만 가져오는 `CoverLikeSerializer`를 만들었습니다.
```python
class CoverLikeSerializer(serializers.ModelSerializer):
    """Serializer for likes of cover"""

    class Meta:
        model = Cover
        fields = [
            "id",
            "likes",
            "like_count",
        ]
```

### Additional documentation

![image](https://user-images.githubusercontent.com/77932817/143436666-9ec91e99-368b-4867-bb41-19c618d2fbe9.png)

2021-11-26 07:40 UTC, ccdc-git requested changes
내용이 많네요. 너무 많으면 제가 줌으로 도와줄게요.

2021-11-26 07:40 UTC, ccdc-git commented on backend/app/band/tests/views/test_cover.py
> +        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
단순히 status코드만 확인하지 말고 내용도 확인해주세요.

2021-11-26 07:40 UTC, ccdc-git commented on backend/app/band/tests/views/test_cover.py
> +                    "audio": None,
audio는 무조건 파일이 들어가야 합니다.

2021-11-26 07:40 UTC, ccdc-git commented on backend/app/band/tests/views/test_cover.py
> +                    "tags": [tag.pk]
tags는 string으로 받아요.

2021-11-26 07:40 UTC, ccdc-git commented on backend/app/band/tests/views/test_cover.py
> +            content_type="application/json",
File을 다루기 때문에 content_type은 form/data입니다.

2021-11-26 07:40 UTC, ccdc-git commented on backend/app/band/serializers.py
> +        return super().create(validated_data)
내부 코드를 보시면 serializer는 결국 ManytoMany를 제외하고는 Model.create와 비슷합니다.
여기서 song을 query를 통해 넣지 않고 그냥 song_id를 넣으면 자동으로 연결 됩니다.

ManyToMany는 방식이 좀 달라서 직접 query해주고 넣어주는게 맞아요.

2021-11-26 07:40 UTC, ccdc-git commented on backend/app/band/views/cover_views.py
> +            data["tags_list"] = data.pop("tags")
data를 받는 content/type이 달라서 다른 처리를 해줘야 합니다. 지금 tags_list는 '["TAG1"]' 이런 string이 나와요.

2021-11-26 07:40 UTC, ccdc-git commented on backend/app/band/views/cover_views.py
> +        user_id = 1  # add user detection
merge는 user까지 수정하고 하는게 좋을 것 같아요.

2021-11-30 19:31 UTC, GoGiants1 approved these changes
고생 많으셨습니다.

2021-12-03 11:11 UTC, zz-zye commented on backend/app/band/tests/views/test_cover.py
> +                    "tags": [tag.pk]
string으로 받을 경우 여러개의 태그는 어떤 식으로 받나요?

2021-12-03 11:12 UTC, zz-zye commented on backend/app/band/serializers.py
> +        return super().create(validated_data)
![image](https://user-images.githubusercontent.com/77932817/144593196-85ab61c6-a310-49d1-a403-ace11146c23e.png)

이런 식으로 하려니 `"Cover.song" must be a "Song" instance.` 라는 식으로 Song을 줘야 한다는 에러가 뜨는 것 같은데, 어떤 식으로 해야 하나요?

2021-12-03 11:23 UTC, ccdc-git commented on backend/app/band/tests/views/test_cover.py
> +                    "tags": [tag.pk]
json포멧으로 받으면 될것 같아요.
다른 요청들은 content 자체가 json 포멧이었는데
이 요청은 file 업로드 때문에 content타입이 달라요

2021-12-03 11:25 UTC, ccdc-git commented on backend/app/band/serializers.py
> +        return super().create(validated_data)
48, 49번 라인을 삭제하고 실행해봐요.
validated_data 안에 song_id 라는 key로 들어가 있으면 될거에요.

2021-12-03 11:43 UTC, zz-zye commented on backend/app/band/serializers.py
> +        return super().create(validated_data)
해결되었습니다! 감사합니다

2021-12-03 20:02 UTC, zz-zye commented
미묘한 버그를 하나 맞닥뜨렸었는데 테스트 때 혹시라도 같은 실수를 하시는 경우가 있을까봐 올립니다

![image](https://user-images.githubusercontent.com/77932817/144665659-f8c4e9d3-cc6c-487f-ad17-544449eeadb9.png)

request 데이터를 만들어서 cover를 만드는 테스트들을 하는데 이제 파일 데이터를 보낼 때 저렇게 하면 된대서 보냈습니다

근데 저렇게 하면 request_data["audio"]에 들어있는 파일이 첫 번째 post 보낸거랑 두 번째 post 보낸 거에 똑같이 들어가는데요, post를 보낼 때 저 파일에 대해 read()가 실행됩니다... 그래서 첫 번째 호출 후에는 저 파일에 대한 파일 포인터가 맨 끝으로 가있게 되죠

그래서 두 번째 호출을 할 때 request_data["audio"]에는 포인터가 파일 끝으로 가 있는 파일, 즉 아무것도 안 들은 거나 마찬가지인 파일이 들어가게 됩니다...

2021-12-03 20:50 UTC, zz-zye commented on backend/app/band/views/cover_views.py
> +            data["tags_list"] = data.pop("tags")
수정했습니다!

2021-12-03 20:50 UTC, zz-zye commented on backend/app/band/tests/views/test_cover.py
> +            content_type="application/json",
수정했습니다! content_type으로 아무것도 안 주면 자동으로 되는군요

2021-12-03 20:50 UTC, zz-zye commented on backend/app/band/tests/views/test_cover.py
> +                    "tags": [tag.pk]
수정했습니다!

2021-12-03 20:51 UTC, zz-zye commented on backend/app/band/tests/views/test_cover.py
> +                    "audio": None,
수정했습니다!
audio에 아무것도 안 넣으면 400 "No audio file."이라고 출력되게 해놓았습니다

2021-12-03 20:51 UTC, zz-zye commented on backend/app/band/tests/views/test_cover.py
> +        self.assertEqual(response.status_code, status.HTTP_201_CREATED)
테스트 코드도 자세하게 수정 완료했습니다.

2021-12-03 20:51 UTC, zz-zye commented on backend/app/band/views/cover_views.py
> +        user_id = 1  # add user detection
수정했습니다

2021-12-04 06:33 UTC, ccdc-git approved these changes
수고하셨습니다.

2021-12-04 13:52 UTC, merged