Backend/user
swsnu/swpp2021-team9 pull request #64
Opened 2021-12-01 18:50 UTC by zz-zye

### Related Issues

Fixes #63 

### Description

정윤님이 작성해주신 `UserSignup`, `UserSignin`, `UserSignout`을 DRF에 따라 고쳤습니다. 제가 DRF가 아직도 안 익숙해서 그런지 미묘한 부분이 좀 있어서 시행착오를 좀 거치긴 했는데 이제 잘 되는 것 같습니다. 또한 `UserInfo` view도 제가 전에 한 cover view와 비슷한 것 같아서 하는 김에 추가했습니다.

테스트 코드도 작성했습니다.
![image](https://user-images.githubusercontent.com/77932817/144295430-2e11badc-f673-466f-b929-b68c390beb08.png)

### Additional documentation

`settings.py`에서 `DEFAULT_PERMISSION_CLASSES`를 `DjangoModelPermissionsOrAnonReadOnly`에서 `IsAuthenticatedOrReadOnly`로 바꿨습니다. 둘 다 로그인 안 한 상태에선 GET 종류만, 로그인 한 상태에선 PUT/POST 종류까지 가능하게 해주는 역할이지만, 전자는 거기에 추가로 View들이 DRF의 queryset을 통해 구현되어야 한다는 조건이 붙는 것 같아서 저희 프로젝트에 굳이 필요하지 않을 것 같았습니다. 테스트 코드를 작성하기에도 후자가 더 편했습니다.

`IsAuthenticatedOrReadOnly`를 활성화함에 따라 테스트 시에도 PUT/POST를 테스트할 때에는 Client를 로그인시켜줘야 합니다. `client.force_login(user)`을 통해 간단하게 할 수 있습니다. 기존에 작성되었던 `test_coverinfo.py`에도 이를 적용시켰습니다. 사실은 제대로 고치려면 PUT cover info를 하는 경우에 현재 로그인한 유저가 cover의 작성자인지 확인하는 절차도 추가시켜야 하지만, 그건 cover를 다루는 이슈에서 해결하도록 하겠습니다.

2021-12-02 05:05 UTC, ccdc-git requested changes
몇가지 확인해주시면 될것 같아요 수고하셨습니다.

2021-12-02 05:05 UTC, ccdc-git commented on backend/app/user/tests.py
> -    def test_user_signout(self):
기능별로 test를 분리한 것 같은데 다시 나눈 이유가 있나요?

2021-12-02 05:05 UTC, ccdc-git commented on backend/app/user/tests.py
> +        user: CustomUser = User.objects.first()
first 로 뽑는것보다 get(pk=1) 이렇게 사용하는게 좋을 것 같아요.

2021-12-02 17:23 UTC, zz-zye commented on backend/app/user/tests.py
> +        new_user: CustomUser = User.objects.last()
수정했습니다!

2021-12-02 17:23 UTC, zz-zye commented on backend/app/user/tests.py
> -    def test_user_signout(self):
signout만 체크하려다가 생각해보니 어차피 signin도 해야 해서 좀 비효율적인 것 같았습니다

2021-12-02 17:55 UTC, zz-zye commented on backend/app/user/tests.py
> +        user: CustomUser = User.objects.first()
수정했습니다

2021-12-03 07:24 UTC, ccdc-git approved these changes
수고하셨습니다.

2021-12-03 07:24 UTC, uzrjny approved these changes
제가 DRF 형식에 익숙하지 않아서 기존 방식대로 코드를 짰는데 태원님이 잘 수정해주신 것 같습니다👍 감사합니다 !

2021-12-03 13:56 UTC, merged